import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SmoothScrollProvider } from "@/components/providers/SmoothScrollProvider";
import { GsapProvider } from "@/components/providers/GsapProvider";
import { LangProvider } from "@/components/providers/LangProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HOTEL BOOKING",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full w-full antialiased`}
    >
      <body className="flex min-h-full min-w-0 w-full flex-col overflow-x-clip">
        <SmoothScrollProvider>
          <GsapProvider>
            <LangProvider>
              <Navbar />
              {children}
              <Footer />
            </LangProvider>
          </GsapProvider>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
